workflows:
  android:
    name: Build APK
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
      java: 17
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
